"""
Seed script – inserts demo companies and candidates into the database.
Run with:  python seed.py
"""
import json
from app import create_app
from app.database import db
from app.models import Company, Candidate, AppSettings

COMPANIES = [
    {
        "name": "TechNova GmbH",
        "industry": "Software Engineering",
        "location": "Berlin, Germany",
        "description": "A fast-growing Berlin-based SaaS company building enterprise productivity tools.",
        "website": "https://technova.example.com",
        "required_skills": ["Python", "Git", "Communication", "English"],
        "min_experience_years": 0,
        "job_requirements": {
            "role": "Software Engineering Intern",
            "duration": "6 months",
            "description": "Support the backend team in building REST APIs. Work with Python, FastAPI, and PostgreSQL.",
        },
    },
    {
        "name": "Marketing Hub Paris",
        "industry": "Digital Marketing",
        "location": "Paris, France",
        "description": "A leading digital marketing agency serving luxury brands across Europe.",
        "website": "https://marketinghub.example.com",
        "required_skills": ["Communication", "Social Media", "French", "Excel"],
        "min_experience_years": 0,
        "job_requirements": {
            "role": "Digital Marketing Intern",
            "duration": "4 months",
            "description": "Assist in managing social media accounts, creating content, and analysing campaign performance.",
        },
    },
    {
        "name": "LogiTrans Barcelona",
        "industry": "Logistics & Supply Chain",
        "location": "Barcelona, Spain",
        "description": "International logistics company specialising in last-mile delivery innovation.",
        "website": "https://logitrans.example.com",
        "required_skills": ["Excel", "Communication", "Data Analysis", "English", "Spanish"],
        "min_experience_years": 0.5,
        "job_requirements": {
            "role": "Supply Chain Analyst Intern",
            "duration": "6 months",
            "description": "Support analysts with data modelling, KPI tracking, and process optimisation.",
        },
    },
    {
        "name": "FinanceFlow Amsterdam",
        "industry": "Financial Services",
        "location": "Amsterdam, Netherlands",
        "description": "Leading fintech company specializing in digital banking solutions and financial analytics.",
        "website": "https://financeflow.example.com",
        "required_skills": ["Excel", "Python", "Financial Analysis", "English", "Data Analysis"],
        "min_experience_years": 0,
        "job_requirements": {
            "role": "Financial Analyst Intern",
            "duration": "5 months",
            "description": "Support the analytics team with financial modeling, reporting, and data visualization using Python and Excel.",
        },
    },
    {
        "name": "EcoDesign Milano",
        "industry": "Sustainable Design",
        "location": "Milan, Italy",
        "description": "Innovative design studio focused on sustainable product development and circular economy solutions.",
        "website": "https://ecodesign.example.com",
        "required_skills": ["Design Thinking", "Communication", "Project Management", "Italian", "English"],
        "min_experience_years": 0,
        "job_requirements": {
            "role": "Design Intern",
            "duration": "6 months",
            "description": "Collaborate with designers on product lifecycle assessments and sustainable material research.",
        },
    },
    {
        "name": "ConsultCorp Madrid",
        "industry": "Management Consulting",
        "location": "Madrid, Spain",
        "description": "Global management consulting firm providing strategic advisory to Fortune 500 companies.",
        "website": "https://consultcorp.example.com",
        "required_skills": ["Business Analysis", "Excel", "Communication", "English", "Spanish"],
        "min_experience_years": 0,
        "job_requirements": {
            "role": "Business Analysis Intern",
            "duration": "5 months",
            "description": "Assist senior consultants with market research, data analysis, and client presentation preparation.",
        },
    },
]

CANDIDATES = [
    # ── TechNova GmbH ──
    {
        "company_name": "TechNova GmbH",
        "name": "Alice Moreau",
        "email": "alice.moreau@example.com",
        "phone": "+33 6 12 34 56 78",
        "status": "done",
        "cv_path": "uploads/alice_moreau_cv.pdf",
        "compatibility_score": 82,
        "risk_level": "Low",
        "experience_years": 1.5,
        "education_level": "Master",
        "ai_analysis": {
            "name": "Alice Moreau",
            "email": "alice.moreau@example.com",
            "phone": "+33 6 12 34 56 78",
            "profile_summary": "Alice is a highly motivated French computer science student in her final year of a Master's degree at Sorbonne University. She combines strong theoretical foundations with practical Python development experience gained during two internships. Her proactive attitude and strong communication skills make her an ideal candidate for a software engineering placement in an international environment.",
            "experience_years": 1.5,
            "education_level": "Master",
            "education_analysis": "Alice holds a Bachelor's degree in Computer Science from Université Paris Diderot and is currently completing a Master's in Software Engineering at Sorbonne University. Her academic focus on distributed systems and backend architecture aligns closely with the requirements of a software engineering internship. She has maintained a GPA of 15.8/20, placing her in the top 15% of her cohort.",
            "experience_analysis": "Alice completed a 4-month internship at Capgemini (Paris) where she built a REST API in Python/FastAPI integrated with a PostgreSQL database, processing over 50K daily transactions. She also worked 6 months at a fintech startup as a part-time developer, implementing automated testing pipelines using pytest and GitHub Actions. These experiences demonstrate practical readiness for a demanding technical internship.",
            "soft_skills_analysis": "Alice communicates clearly in both French and English, demonstrated by her role as team lead in her university's student tech club. She is highly organised, consistently delivering projects on deadline, and adapts quickly to new technical environments.",
            "strengths_analysis": "Alice's strongest asset is her Python expertise backed by real production experience. Her investment in open-source projects — including a 120-star GitHub repository — signals genuine passion and self-direction beyond coursework.",
            "weaknesses_analysis": "Alice has limited experience with cloud infrastructure (AWS/GCP), which may require onboarding time. Her exposure to agile methodologies has been informal; structured sprint workflows may be a learning curve.",
            "risk_assessment": "Risk of placement failure is low. Alice has proven delivery capabilities in professional settings, strong academic credentials, and an international mindset. The primary risk factor is her limited cloud experience, which TechNova's team can address in the first weeks.",
            "languages": [
                {"language": "French", "level": "Native", "evidence": "French native speaker stated on CV"},
                {"language": "English", "level": "C1", "evidence": "TOEFL score 105/120 listed under certifications"},
                {"language": "German", "level": "A2", "evidence": "Currently attending German language evening classes"},
            ],
            "skills": [
                {"name": "Python", "category": "Tech Stack", "level": 3, "level_label": "Strong", "evidence": "Built REST API in Python/FastAPI at Capgemini, processing 50K daily transactions", "requirement_desc": "Core language for backend development"},
                {"name": "Git", "category": "Tech Stack", "level": 3, "level_label": "Strong", "evidence": "Implemented CI/CD pipelines using GitHub Actions during fintech internship", "requirement_desc": "Version control and collaboration"},
                {"name": "Communication", "category": "Soft Skills", "level": 3, "level_label": "Strong", "evidence": "Team lead for university tech club, 30 members", "requirement_desc": "Cross-team collaboration"},
                {"name": "English", "category": "Language", "level": 3, "level_label": "Strong", "evidence": "TOEFL 105/120", "requirement_desc": "Working language in international team"},
                {"name": "PostgreSQL", "category": "Tech Stack", "level": 2, "level_label": "Average", "evidence": "Used PostgreSQL as the primary database during Capgemini internship", "requirement_desc": "Database for backend projects"},
            ],
            "compatibility_checks": [
                {"criteria": "Education Level", "status": "compatible", "explanation": "Alice holds a Master's degree in Software Engineering, meeting and exceeding the typical internship requirement for a technical role at TechNova."},
                {"criteria": "Years of Experience", "status": "compatible", "explanation": "1.5 years of cumulative internship experience (Capgemini + fintech startup) meets the minimum threshold and demonstrates real-world delivery capability."},
                {"criteria": "Communication Skills", "status": "compatible", "explanation": "Leadership of a 30-member student tech club and a C1 English TOEFL score confirm strong communication abilities in a professional context."},
                {"criteria": "International Readiness", "status": "compatible", "explanation": "Alice has actively prepared for an international experience by learning German and participating in Erasmus+ exchange programme preparation."},
                {"criteria": "Technical Skills", "status": "compatible", "explanation": "Python, FastAPI, PostgreSQL, and Git are all confirmed on the CV through specific project evidence, directly matching TechNova's tech stack."},
            ],
            "compatibility_score": 82,
            "risk_level": "Low",
        },
    },
    {
        "company_name": "TechNova GmbH",
        "name": "Karim Benali",
        "email": "karim.benali@example.com",
        "phone": "+213 555 123 456",
        "status": "done",
        "cv_path": "uploads/karim_benali_cv.pdf",
        "compatibility_score": 55,
        "risk_level": "Medium",
        "experience_years": 0,
        "education_level": "Bachelor",
        "ai_analysis": {
            "name": "Karim Benali",
            "email": "karim.benali@example.com",
            "profile_summary": "Karim is a third-year Computer Science student at the University of Algiers, motivated and eager to gain his first professional experience abroad. While he lacks professional internship experience, he has built several personal projects demonstrating initiative. His main challenges are limited English proficiency and no professional Python exposure, which represent areas requiring attention.",
            "experience_years": 0,
            "education_level": "Bachelor",
            "education_analysis": "Karim is in his third year of a Bachelor's in Computer Science with a GPA of 13.5/20. His curriculum covers algorithms, data structures, and web development fundamentals, providing a solid theoretical base.",
            "experience_analysis": "Karim has no professional internship experience. However, he built a personal portfolio website using Flask and a small task-management app in Python, which he published on GitHub. These self-initiated projects demonstrate curiosity and a learning-oriented mindset, but do not substitute for professional delivery experience.",
            "soft_skills_analysis": "Karim demonstrates self-motivation through his independent projects. However, his CV shows limited evidence of collaborative work or cross-functional communication, which is a gap for a team-based internship.",
            "strengths_analysis": "Strong foundational knowledge in algorithms and data structures. Personal projects in Python/Flask show initiative. Highly motivated to prove himself internationally.",
            "weaknesses_analysis": "No professional internship experience is Karim's primary gap. His English is listed as 'intermediate' with no certification provided; this may hinder communication in a German team environment. No evidence of version control (Git) usage.",
            "risk_assessment": "Medium risk. Karim has the technical curiosity to succeed but requires more structure and mentoring than an average intern. The language barrier and lack of collaborative experience could slow his integration. Boarding advisors should probe language readiness carefully.",
            "languages": [
                {"language": "Arabic", "level": "Native", "evidence": "Native language"},
                {"language": "French", "level": "B1", "evidence": "French listed as second language"},
                {"language": "English", "level": "B1", "evidence": "Self-assessed as intermediate, no certification"},
            ],
            "skills": [
                {"name": "Python", "category": "Tech Stack", "level": 1, "level_label": "Basic", "evidence": "Built personal Flask task-management app (personal GitHub project)", "requirement_desc": "Core language for backend development"},
                {"name": "Git", "category": "Tech Stack", "level": 1, "level_label": "Basic", "evidence": "Not explicitly mentioned; inferred from GitHub profile", "requirement_desc": "Version control and collaboration"},
                {"name": "Communication", "category": "Soft Skills", "level": 1, "level_label": "Basic", "evidence": "No evidence of team or presentation experience on CV", "requirement_desc": "Cross-team collaboration"},
                {"name": "English", "category": "Language", "level": 2, "level_label": "Average", "evidence": "Self-assessed as intermediate, no formal certification provided", "requirement_desc": "Working language in international team"},
            ],
            "compatibility_checks": [
                {"criteria": "Education Level", "status": "compatible", "explanation": "Currently completing a Bachelor's in CS — meets the minimum academic requirement for a junior internship role."},
                {"criteria": "Years of Experience", "status": "incompatible", "explanation": "Zero professional internship experience. Personal projects exist but do not constitute formal professional delivery."},
                {"criteria": "Communication Skills", "status": "partial", "explanation": "Intermediate English (self-assessed, uncertified) and no evidence of collaborative projects raise concerns about professional communication readiness."},
                {"criteria": "International Readiness", "status": "partial", "explanation": "No prior international exposure documented. Motivation is expressed but unsubstantiated by actions such as language courses or exchange programmes."},
                {"criteria": "Technical Skills", "status": "partial", "explanation": "Python basics confirmed via personal projects, but no Git, no CI/CD, and no professional context — significantly below TechNova's typical intern baseline."},
            ],
            "compatibility_score": 55,
            "risk_level": "Medium",
        },
    },
    {
        "company_name": "TechNova GmbH",
        "name": "Eva Schmidt",
        "email": "eva.schmidt@example.com",
        "phone": "+49 179 123 4567",
        "status": "done",
        "cv_path": "uploads/eva_schmidt_cv.pdf",
        "compatibility_score": 76,
        "risk_level": "Low",
        "experience_years": 1,
        "education_level": "Bachelor",
        "ai_analysis": {
            "name": "Eva Schmidt",
            "email": "eva.schmidt@example.com",
            "profile_summary": "Eva is a German Computer Science student in her final year at Technical University of Munich. With practical experience in full-stack development and strong Git/CI-CD knowledge, she represents a solid mid-tier match for TechNova's backend engineering role. Her proximity to Berlin and native German background provide additional integration benefits.",
            "experience_years": 1,
            "education_level": "Bachelor",
            "experience_analysis": "Eva completed a 3-month internship at a Berlin-based startup where she built microservices in Python and deployed them to AWS using Docker and GitHub Actions. She also contributed to several open-source projects with focus on API development.",
            "soft_skills_analysis": "Eva is pragmatic and results-oriented. She has presented technical findings at university seminars and communicates clearly in both German and English.",
            "strengths_analysis": "Strong DevOps mindset with hands-on Docker/Kubernetes exposure. Fluent in Python and Git workflows.",
            "weaknesses_analysis": "Limited database optimization experience. PostgreSQL exposure is basic.",
            "risk_assessment": "Low risk. Eva has relevant technical skills and cultural familiarity with the German working environment.",
            "languages": [
                {"language": "German", "level": "Native", "evidence": "German native speaker"},
                {"language": "English", "level": "B2+", "evidence": "Cambridge B2 certificate"},
            ],
            "skills": [
                {"name": "Python", "category": "Tech Stack", "level": 2, "level_label": "Average", "evidence": "Built microservices in Python at startup internship"},
                {"name": "Git", "category": "Tech Stack", "level": 3, "level_label": "Strong", "evidence": "Daily use of Git and GitHub Actions in professional project"},
                {"name": "Communication", "category": "Soft Skills", "level": 2, "level_label": "Average", "evidence": "Presented technical findings at university seminars"},
                {"name": "English", "category": "Language", "level": 2, "level_label": "Average", "evidence": "Cambridge B2 certificate"},
            ],
            "compatibility_checks": [
                {"criteria": "Education Level", "status": "compatible", "explanation": "Final year Bachelor's in CS with focus on software engineering"},
                {"criteria": "Years of Experience", "status": "compatible", "explanation": "1 year of professional internship experience in backend engineering"},
                {"criteria": "Technical Skills", "status": "compatible", "explanation": "Python, Git, Docker, and AWS experience match TechNova's tech stack"},
                {"criteria": "International Readiness", "status": "compatible", "explanation": "Native German, English B2+, and prior startup experience in Berlin"},
                {"criteria": "Communication Skills", "status": "compatible", "explanation": "Clear communicator with technical presentation experience"},
            ],
            "compatibility_score": 76,
            "risk_level": "Low",
        },
    },
    # ── Marketing Hub Paris ──
    {
        "company_name": "Marketing Hub Paris",
        "name": "Sofia Lindqvist",
        "email": "sofia.l@example.com",
        "phone": "+46 70 123 45 67",
        "status": "done",
        "cv_path": "uploads/sofia_lindqvist_cv.pdf",
        "compatibility_score": 91,
        "risk_level": "Low",
        "experience_years": 2,
        "education_level": "Master",
        "ai_analysis": {
            "name": "Sofia Lindqvist",
            "email": "sofia.l@example.com",
            "profile_summary": "Sofia is a Swedish marketing professional completing a dual Master's in Digital Marketing and Communication at Stockholm University. With two years of practical experience managing social media accounts and running paid campaigns, she is an exceptionally strong match for the Marketing Hub Paris internship position. Her trilingual profile (English, French, Swedish) is a major differentiator.",
            "experience_years": 2,
            "education_level": "Master",
            "education_analysis": "Sofia is completing a dual Master's degree combining Digital Marketing and Strategic Communication, with a specialisation in luxury brand management — directly relevant to Marketing Hub Paris's client portfolio.",
            "experience_analysis": "Sofia managed social media channels for an e-commerce brand (60K+ followers), grew organic reach by 40% in 6 months, and ran Meta Ads campaigns with budgets up to €5,000/month. She also completed a 6-month internship at a Stockholm PR agency handling 4 international accounts.",
            "soft_skills_analysis": "Sofia is an exceptional communicator with demonstrated client-facing experience. Her project management skills are evidenced by simultaneous management of 4 client accounts during her PR internship.",
            "strengths_analysis": "Trilingual profile, luxury brand marketing exposure, and measurable social media results (40% organic growth) make Sofia a top-tier candidate. Her French proficiency gives her a direct cultural advantage for the Paris placement.",
            "weaknesses_analysis": "Sofia's experience is predominantly B2C; Marketing Hub Paris also serves B2B clients. This is a minor gap that can be addressed through onboarding.",
            "risk_assessment": "Extremely low risk. Sofia brings experience, language skills, and cultural fit that go beyond typical intern expectations. She is likely to add immediate value from day one.",
            "languages": [
                {"language": "Swedish", "level": "Native", "evidence": "Swedish native speaker"},
                {"language": "English", "level": "C2", "evidence": "Cambridge C2 Proficiency certificate"},
                {"language": "French", "level": "B2", "evidence": "DELF B2 certificate obtained 2023"},
            ],
            "skills": [
                {"name": "Social Media", "category": "Marketing", "level": 3, "level_label": "Strong", "evidence": "Managed 60K-follower account, 40% organic growth in 6 months", "requirement_desc": "Core requirement for digital marketing role"},
                {"name": "French", "category": "Language", "level": 3, "level_label": "Strong", "evidence": "DELF B2 certificate 2023", "requirement_desc": "Working language in Paris office"},
                {"name": "Excel", "category": "Tools", "level": 3, "level_label": "Strong", "evidence": "Used Excel for weekly KPI reporting across 4 client accounts", "requirement_desc": "Reporting and data analysis"},
                {"name": "Communication", "category": "Soft Skills", "level": 3, "level_label": "Strong", "evidence": "Client-facing role managing 4 international accounts at PR agency", "requirement_desc": "Client and team communication"},
            ],
            "compatibility_checks": [
                {"criteria": "Education Level", "status": "compatible", "explanation": "Dual Master's in Digital Marketing and Communication — exceeds the educational requirement."},
                {"criteria": "Years of Experience", "status": "compatible", "explanation": "2 years of combined professional and internship experience in digital marketing."},
                {"criteria": "Communication Skills", "status": "compatible", "explanation": "C2 English and B2 French with client-facing experience across international accounts."},
                {"criteria": "International Readiness", "status": "compatible", "explanation": "Multilingual, has worked with international clients, and is actively seeking a Paris placement."},
                {"criteria": "Technical Skills", "status": "compatible", "explanation": "Social media management, Meta Ads, Excel — all core tools for the Digital Marketing Intern role are confirmed."},
            ],
            "compatibility_score": 91,
            "risk_level": "Low",
        },
    },
    {
        "company_name": "Marketing Hub Paris",
        "name": "Lucas Durand",
        "email": "lucas.durand@example.com",
        "phone": "+33 6 78 90 12 34",
        "status": "done",
        "cv_path": "uploads/lucas_durand_cv.pdf",
        "compatibility_score": 67,
        "risk_level": "Medium",
        "experience_years": 0.5,
        "education_level": "Bachelor",
        "ai_analysis": {
            "name": "Lucas Durand",
            "email": "lucas.durand@example.com",
            "profile_summary": "Lucas is a French communications student in his final year at Paris-Sorbonne University. He shows strong potential in content creation and social media strategy with a 2-month internship experience. His native French and growing English skills make him moderately suitable for Marketing Hub Paris.",
            "experience_years": 0.5,
            "education_level": "Bachelor",
            "experience_analysis": "Lucas interned for 2 months at a Parisian boutique marketing agency where he managed Instagram accounts for 3 local fashion brands. He created 50+ posts and increased engagement by 25%.",
            "soft_skills_analysis": "Lucas is creative and enthusiastic about digital content. He participates in university marketing projects.",
            "strengths_analysis": "Native French speaker, creative portfolio, social media familiarity.",
            "weaknesses_analysis": "Limited formal analytics knowledge. No Meta Ads experience. Excel skills not demonstrated.",
            "risk_assessment": "Medium risk. Lucas has enthusiasm and foundational skills but lacks breadth of experience in paid campaigns and data analytics.",
            "languages": [
                {"language": "French", "level": "Native", "evidence": "French native speaker"},
                {"language": "English", "level": "B1+", "evidence": "TOEIC 750/990"},
            ],
            "skills": [
                {"name": "Social Media", "category": "Marketing", "level": 2, "level_label": "Average", "evidence": "Managed Instagram for 3 brands, 25% engagement increase"},
                {"name": "Communication", "category": "Soft Skills", "level": 2, "level_label": "Average", "evidence": "University marketing project participation"},
                {"name": "English", "category": "Language", "level": 2, "level_label": "Average", "evidence": "TOEIC 750/990"},
            ],
            "compatibility_checks": [
                {"criteria": "Education Level", "status": "compatible", "explanation": "Bachelor's in Communications meets basic requirement"},
                {"criteria": "Years of Experience", "status": "partial", "explanation": "Only 2 months of formal experience, though enthusiastic"},
                {"criteria": "Communication Skills", "status": "compatible", "explanation": "Native French, good English (B1+)"},
                {"criteria": "Technical Skills", "status": "partial", "explanation": "Social media basics confirmed, but lacks analytics and paid campaign experience"},
            ],
            "compatibility_score": 67,
            "risk_level": "Medium",
        },
    },
    # ── LogiTrans Barcelona ──
    {
        "company_name": "LogiTrans Barcelona",
        "name": "Omar Hassan",
        "email": "omar.h@example.com",
        "phone": "+212 600 789 456",
        "status": "done",
        "cv_path": "uploads/omar_hassan_cv.pdf",
        "compatibility_score": 38,
        "risk_level": "High",
        "experience_years": 0,
        "education_level": "Bachelor",
        "ai_analysis": {
            "name": "Omar Hassan",
            "email": "omar.h@example.com",
            "profile_summary": "Omar is a final-year Bachelor's student in Business Administration from Casablanca. While he presents as motivated, his CV reveals significant gaps relative to the LogiTrans Barcelona requirements: no experience in logistics or supply chain, no English certification, no Spanish, and no Data Analysis experience. The placement carries a high risk of underperformance.",
            "experience_years": 0,
            "education_level": "Bachelor",
            "education_analysis": "Omar is completing a Bachelor's in Business Administration with a general management focus. His curriculum includes basic accounting, management principles, and business law — with no specialisation in supply chain or logistics.",
            "experience_analysis": "Omar completed a 2-month summer internship at a local retail company in Casablanca assisting with inventory counts. No data analysis or supply chain project is documented.",
            "soft_skills_analysis": "Limited evidence of communication skills in English or Spanish. No leadership or collaborative project evidence found on the CV.",
            "strengths_analysis": "Omar shows willingness to take on new challenges. His internship experience, though brief, shows he has some exposure to inventory management basics.",
            "weaknesses_analysis": "Critical gaps: no Spanish, no English certification, no prior exposure to data or supply chain tools, and only 2 months of tangentially relevant experience. These gaps represent multiple simultaneous onboarding challenges.",
            "risk_assessment": "High risk. Without Spanish (the working language) and with no supply chain or data analysis background, Omar would require disproportionate mentoring resources and is unlikely to be productive within the internship window. Boarding advisors should discuss whether additional preparation is required before this placement.",
            "languages": [
                {"language": "Arabic", "level": "Native", "evidence": "Native language"},
                {"language": "French", "level": "B2", "evidence": "Listed as professional proficiency"},
                {"language": "English", "level": "A2", "evidence": "Self-assessed as basic, no certification"},
            ],
            "skills": [
                {"name": "Excel", "category": "Tools", "level": 1, "level_label": "Basic", "evidence": "Used Excel for inventory tracking during retail internship", "requirement_desc": "KPI reporting and data analysis"},
                {"name": "Communication", "category": "Soft Skills", "level": 1, "level_label": "Basic", "evidence": "No documented communication experience beyond course work", "requirement_desc": "Team and stakeholder communication"},
                {"name": "Data Analysis", "category": "Analytics", "level": 1, "level_label": "Basic", "evidence": "No data analysis experience documented", "requirement_desc": "Core function of the supply chain analyst role"},
            ],
            "compatibility_checks": [
                {"criteria": "Education Level", "status": "partial", "explanation": "Business Administration degree is broadly relevant but lacks any supply chain or logistics specialisation."},
                {"criteria": "Years of Experience", "status": "incompatible", "explanation": "Only 2 months of tangentially relevant internship experience — far below the 6-month minimum expected for this role."},
                {"criteria": "Communication Skills", "status": "incompatible", "explanation": "No English certification and no Spanish — both are required working languages at LogiTrans Barcelona."},
                {"criteria": "International Readiness", "status": "partial", "explanation": "Omar has expressed motivation but has no documented international exposure or language preparation for a Spanish-speaking environment."},
                {"criteria": "Technical Skills", "status": "incompatible", "explanation": "Basic Excel only — no data analysis tools, supply chain software, or relevant analytical experience found on CV."},
            ],
            "compatibility_score": 38,
            "risk_level": "High",
        },
    },
    {
        "company_name": "LogiTrans Barcelona",
        "name": "Isabella Rossini",
        "email": "isabella.rossini@example.com",
        "phone": "+34 612 345 678",
        "status": "done",
        "cv_path": "uploads/isabella_rossini_cv.pdf",
        "compatibility_score": 79,
        "risk_level": "Low",
        "experience_years": 1.5,
        "education_level": "Master",
        "ai_analysis": {
            "name": "Isabella Rossini",
            "email": "isabella.rossini@example.com",
            "profile_summary": "Isabella is an Italian supply chain management specialist completing a Master's degree in Operations and Supply Chain Management at Barcelona School of Economics. With 1.5 years of direct logistics experience and fluency in Spanish, she represents an excellent fit for LogiTrans Barcelona's supply chain analyst role.",
            "experience_years": 1.5,
            "education_level": "Master",
            "experience_analysis": "Isabella interned at a major logistics hub in Madrid for 4 months, where she analyzed supplier performance metrics using Excel and Tableau. She also worked part-time for 8 months at a Barcelona-based logistics company managing inventory data.",
            "soft_skills_analysis": "Isabella is detail-oriented and analytical. She has presented logistics optimization findings to senior management.",
            "strengths_analysis": "Domain expertise in supply chain, fluent Spanish and English, hands-on experience with analytical tools.",
            "weaknesses_analysis": "Limited exposure to advanced data science methods (Python, SQL). Business acumen could be developed further.",
            "risk_assessment": "Low risk. Isabella brings domain expertise, language proficiency, and relevant experience.",
            "languages": [
                {"language": "Italian", "level": "Native", "evidence": "Italian native speaker"},
                {"language": "Spanish", "level": "C1", "evidence": "Living and studying in Barcelona for 2 years"},
                {"language": "English", "level": "C1", "evidence": "Cambridge C1 Advanced certificate"},
            ],
            "skills": [
                {"name": "Excel", "category": "Tools", "level": 3, "level_label": "Strong", "evidence": "Daily use for KPI tracking and reporting"},
                {"name": "Data Analysis", "category": "Analytics", "level": 2, "level_label": "Average", "evidence": "Tableau visualization and Excel analysis"},
                {"name": "Communication", "category": "Soft Skills", "level": 2, "level_label": "Average", "evidence": "Presented findings to management"},
                {"name": "Spanish", "category": "Language", "level": 3, "level_label": "Strong", "evidence": "C1 proficiency after 2 years in Barcelona"},
            ],
            "compatibility_checks": [
                {"criteria": "Education Level", "status": "compatible", "explanation": "Master's in Operations and Supply Chain Management directly relevant"},
                {"criteria": "Years of Experience", "status": "compatible", "explanation": "1.5 years of direct supply chain and logistics experience"},
                {"criteria": "Communication Skills", "status": "compatible", "explanation": "C1 English and Spanish with management presentation experience"},
                {"criteria": "Technical Skills", "status": "compatible", "explanation": "Excel, Tableau, and analytical mindset demonstrated"},
                {"criteria": "International Readiness", "status": "compatible", "explanation": "Currently based in Barcelona, trilingual, adapted to international environment"},
            ],
            "compatibility_score": 79,
            "risk_level": "Low",
        },
    },
    # ── FinanceFlow Amsterdam ──
    {
        "company_name": "FinanceFlow Amsterdam",
        "name": "Henrik Andersen",
        "email": "henrik.andersen@example.com",
        "phone": "+31 6 12345678",
        "status": "done",
        "cv_path": "uploads/henrik_andersen_cv.pdf",
        "compatibility_score": 85,
        "risk_level": "Low",
        "experience_years": 1,
        "education_level": "Master",
        "ai_analysis": {
            "name": "Henrik Andersen",
            "email": "henrik.andersen@example.com",
            "profile_summary": "Henrik is a Danish finance professional completing a Master's in Financial Economics at the University of Amsterdam. With strong analytical skills, Python programming experience, and 1 year of fintech exposure, he is an excellent match for FinanceFlow's analytical internship.",
            "experience_years": 1,
            "education_level": "Master",
            "experience_analysis": "Henrik completed a 5-month internship at a Copenhagen-based fintech startup where he built financial models in Python and Excel, analyzing cryptocurrency market trends. He also worked part-time at a Dutch bank analyzing mortgage portfolios.",
            "soft_skills_analysis": "Henrik is methodical and detail-oriented. He communicates complex financial concepts clearly.",
            "strengths_analysis": "Strong Python skills combined with financial domain knowledge. Proficiency in both quantitative and qualitative analysis.",
            "weaknesses_analysis": "Limited exposure to corporate risk management frameworks.",
            "risk_assessment": "Low risk. Henrik brings relevant technical and domain expertise.",
            "languages": [
                {"language": "Danish", "level": "Native", "evidence": "Danish native speaker"},
                {"language": "English", "level": "C1", "evidence": "Fluent, educated in Amsterdam"},
                {"language": "Dutch", "level": "B1", "evidence": "B1 certification"},
            ],
            "skills": [
                {"name": "Python", "category": "Tech Stack", "level": 2, "level_label": "Average", "evidence": "Built financial models in Python"},
                {"name": "Excel", "category": "Tools", "level": 3, "level_label": "Strong", "evidence": "Advanced Excel for financial modeling"},
                {"name": "Financial Analysis", "category": "Finance", "level": 2, "level_label": "Average", "evidence": "Market analysis and portfolio evaluation"},
                {"name": "Data Analysis", "category": "Analytics", "level": 2, "level_label": "Average", "evidence": "Cryptocurrency market trend analysis"},
            ],
            "compatibility_checks": [
                {"criteria": "Education Level", "status": "compatible", "explanation": "Master's in Financial Economics highly relevant"},
                {"criteria": "Years of Experience", "status": "compatible", "explanation": "1 year fintech and banking experience"},
                {"criteria": "Technical Skills", "status": "compatible", "explanation": "Python, Excel, and analytical tools demonstrated"},
                {"criteria": "Communication Skills", "status": "compatible", "explanation": "C1 English, clear communicator"},
            ],
            "compatibility_score": 85,
            "risk_level": "Low",
        },
    },
    {
        "company_name": "FinanceFlow Amsterdam",
        "name": "Mei Chen",
        "email": "mei.chen@example.com",
        "phone": "+31 6 87654321",
        "status": "done",
        "cv_path": "uploads/mei_chen_cv.pdf",
        "compatibility_score": 71,
        "risk_level": "Medium",
        "experience_years": 0,
        "education_level": "Bachelor",
        "ai_analysis": {
            "name": "Mei Chen",
            "email": "mei.chen@example.com",
            "profile_summary": "Mei is a third-year Finance student from Taiwan currently studying at Amsterdam University. She demonstrates strong quantitative skills and growing analytical capability. Her main gaps are limited professional experience and beginner-level English communication.",
            "experience_years": 0,
            "education_level": "Bachelor",
            "experience_analysis": "Mei has no formal internship experience but has completed numerous financial case studies and mathematical modeling assignments at university.",
            "soft_skills_analysis": "Mei is quiet but focused. She participates in university finance club activities.",
            "strengths_analysis": "Strong math background, growing Python skills through university coursework.",
            "weaknesses_analysis": "No professional experience, elementary English proficiency may limit communication.",
            "risk_assessment": "Medium risk. Mei has potential but requires significant mentoring and language support.",
            "languages": [
                {"language": "Chinese", "level": "Native", "evidence": "Native Mandarin speaker"},
                {"language": "English", "level": "B1", "evidence": "B1 test score 72/100"},
                {"language": "Dutch", "level": "A2", "evidence": "Currently learning Dutch"},
            ],
            "skills": [
                {"name": "Excel", "category": "Tools", "level": 2, "level_label": "Average", "evidence": "University coursework assignments"},
                {"name": "Python", "category": "Tech Stack", "level": 1, "level_label": "Basic", "evidence": "Currently learning in university courses"},
                {"name": "Financial Analysis", "category": "Finance", "level": 1, "level_label": "Basic", "evidence": "Academic case studies"},
            ],
            "compatibility_checks": [
                {"criteria": "Education Level", "status": "compatible", "explanation": "Bachelor's in Finance is relevant"},
                {"criteria": "Years of Experience", "status": "incompatible", "explanation": "No professional experience"},
                {"criteria": "Technical Skills", "status": "partial", "explanation": "Excel and Python basics from coursework only"},
                {"criteria": "Communication Skills", "status": "partial", "explanation": "B1 English may require language support"},
            ],
            "compatibility_score": 71,
            "risk_level": "Medium",
        },
    },
    # ── EcoDesign Milano ──
    {
        "company_name": "EcoDesign Milano",
        "name": "Francesca Bruno",
        "email": "francesca.bruno@example.com",
        "phone": "+39 345 123 4567",
        "status": "done",
        "cv_path": "uploads/francesca_bruno_cv.pdf",
        "compatibility_score": 88,
        "risk_level": "Low",
        "experience_years": 1.5,
        "education_level": "Master",
        "ai_analysis": {
            "name": "Francesca Bruno",
            "email": "francesca.bruno@example.com",
            "profile_summary": "Francesca is an Italian sustainable design specialist completing a Master's in Ecological Product Design at Politecnico di Milano. With 1.5 years of hands-on experience in green product development and strong design thinking methodology, she is an excellent cultural and professional fit for EcoDesign Milano.",
            "experience_years": 1.5,
            "education_level": "Master",
            "experience_analysis": "Francesca completed a 4-month internship at an Italian eco-packaging company where she conducted material lifecycle assessments and designed sustainable packaging solutions. She also freelanced on 3 green design projects.",
            "soft_skills_analysis": "Francesca is collaborative and creative. She leads design workshops and communicates sustainability concepts effectively.",
            "strengths_analysis": "Deep sustainability knowledge, Italian base, proven design portfolio, excellent stakeholder communication.",
            "weaknesses_analysis": "Limited experience with data-driven design metrics.",
            "risk_assessment": "Low risk. Francesca brings passion, expertise, and cultural alignment with the company.",
            "languages": [
                {"language": "Italian", "level": "Native", "evidence": "Native Italian speaker"},
                {"language": "English", "level": "C1", "evidence": "Cambridge Advanced certificate"},
            ],
            "skills": [
                {"name": "Design Thinking", "category": "Design", "level": 3, "level_label": "Strong", "evidence": "Leadership of design workshops"},
                {"name": "Communication", "category": "Soft Skills", "level": 3, "level_label": "Strong", "evidence": "Stakeholder presentations and team collaboration"},
                {"name": "Project Management", "category": "Management", "level": 2, "level_label": "Average", "evidence": "Managed 3 freelance design projects"},
                {"name": "Italian", "category": "Language", "level": 3, "level_label": "Strong", "evidence": "Native speaker"},
            ],
            "compatibility_checks": [
                {"criteria": "Education Level", "status": "compatible", "explanation": "Master's in Ecological Product Design directly aligned"},
                {"criteria": "Years of Experience", "status": "compatible", "explanation": "1.5 years of relevant eco-design experience"},
                {"criteria": "Communication Skills", "status": "compatible", "explanation": "Native Italian, C1 English, proven presentation skills"},
                {"criteria": "International Readiness", "status": "compatible", "explanation": "Based in Italy, multilingual, sustainability-minded"},
            ],
            "compatibility_score": 88,
            "risk_level": "Low",
        },
    },
    # ── ConsultCorp Madrid ──
    {
        "company_name": "ConsultCorp Madrid",
        "name": "Carlos Martinez",
        "email": "carlos.martinez@example.com",
        "phone": "+34 666 789 123",
        "status": "done",
        "cv_path": "uploads/carlos_martinez_cv.pdf",
        "compatibility_score": 81,
        "risk_level": "Low",
        "experience_years": 1,
        "education_level": "Master",
        "ai_analysis": {
            "name": "Carlos Martinez",
            "email": "carlos.martinez@example.com",
            "profile_summary": "Carlos is a Spanish business analyst completing a Master's in Management at IE Business School Madrid. With 1 year of consulting exposure, strong analytical capabilities, and native Spanish/fluent English, he is an excellent match for ConsultCorp's business analysis role.",
            "experience_years": 1,
            "education_level": "Master",
            "experience_analysis": "Carlos completed a 4-month internship at a Madrid management consulting firm where he conducted market research, built financial models, and prepared client presentations. He also worked on 2 university consulting projects for local companies.",
            "soft_skills_analysis": "Carlos is articulate and structured in his analytical approach. He has led presentations to C-suite executives during his internship.",
            "strengths_analysis": "Strong business acumen, excellent presentation skills, native Spanish and fluent English, proven consulting exposure.",
            "weaknesses_analysis": "Limited statistical modeling experience.",
            "risk_assessment": "Low risk. Carlos demonstrates consulting readiness and cultural fit.",
            "languages": [
                {"language": "Spanish", "level": "Native", "evidence": "Native Spanish speaker"},
                {"language": "English", "level": "C1", "evidence": "Cambridge C1 Advanced"},
            ],
            "skills": [
                {"name": "Business Analysis", "category": "Consulting", "level": 2, "level_label": "Average", "evidence": "Market research and analysis in consulting internship"},
                {"name": "Excel", "category": "Tools", "level": 3, "level_label": "Strong", "evidence": "Advanced financial modeling"},
                {"name": "Communication", "category": "Soft Skills", "level": 3, "level_label": "Strong", "evidence": "Executive presentations during internship"},
                {"name": "Spanish", "category": "Language", "level": 3, "level_label": "Strong", "evidence": "Native speaker"},
            ],
            "compatibility_checks": [
                {"criteria": "Education Level", "status": "compatible", "explanation": "Master's in Management from prestigious business school"},
                {"criteria": "Years of Experience", "status": "compatible", "explanation": "1 year of direct consulting experience"},
                {"criteria": "Communication Skills", "status": "compatible", "explanation": "Native Spanish, C1 English, executive presentation experience"},
                {"criteria": "Technical Skills", "status": "compatible", "explanation": "Advanced Excel and market research capabilities"},
            ],
            "compatibility_score": 81,
            "risk_level": "Low",
        },
    },
    {
        "company_name": "ConsultCorp Madrid",
        "name": "Elena Vasquez",
        "email": "elena.vasquez@example.com",
        "phone": "+34 655 432 109",
        "status": "done",
        "cv_path": "uploads/elena_vasquez_cv.pdf",
        "compatibility_score": 63,
        "risk_level": "Medium",
        "experience_years": 0.5,
        "education_level": "Bachelor",
        "ai_analysis": {
            "name": "Elena Vasquez",
            "email": "elena.vasquez@example.com",
            "profile_summary": "Elena is a Spanish economics graduate with 2 months of field experience in market research. She shows interest in consulting but lacks depth of analytical experience. Her main ceiling is limited professional exposure and developing English skills.",
            "experience_years": 0.5,
            "education_level": "Bachelor",
            "experience_analysis": "Elena completed a 2-month market research internship at a Madrid research firm where she conducted surveys and compiled data reports.",
            "soft_skills_analysis": "Elena is willing and organized but documentation shows limited presentation or client interaction experience.",
            "strengths_analysis": "Native Spanish, organized, interest in business analysis.",
            "weaknesses_analysis": "Minimal professional experience (2 months), limited English proficiency (B1), basic analytical skills.",
            "risk_assessment": "Medium risk. Elena would require substantial mentoring in consulting methodology and English language.",
            "languages": [
                {"language": "Spanish", "level": "Native", "evidence": "Native Spanish speaker"},
                {"language": "English", "level": "B1", "evidence": "B1 English certificate"},
            ],
            "skills": [
                {"name": "Excel", "category": "Tools", "level": 1, "level_label": "Basic", "evidence": "Basic spreadsheet work in market research internship"},
                {"name": "Communication", "category": "Soft Skills", "level": 1, "level_label": "Basic", "evidence": "Survey administration experience"},
                {"name": "Business Analysis", "category": "Consulting", "level": 1, "level_label": "Basic", "evidence": "Data compilation in internship"},
            ],
            "compatibility_checks": [
                {"criteria": "Education Level", "status": "compatible", "explanation": "Bachelor's in Economics is foundational"},
                {"criteria": "Years of Experience", "status": "incompatible", "explanation": "Only 2 months of experience, below threshold"},
                {"criteria": "Communication Skills", "status": "partial", "explanation": "Native Spanish good, but B1 English limits international consulting work"},
                {"criteria": "Technical Skills", "status": "partial", "explanation": "Basic Excel and analysis only"},
            ],
            "compatibility_score": 63,
            "risk_level": "Medium",
        },
    },
    {
        "company_name": "TechNova GmbH",
        "name": "Karim Benali",
        "email": "karim.benali@example.com",
        "phone": "+213 555 123 456",
        "status": "done",
        "compatibility_score": 55,
        "risk_level": "Medium",
        "experience_years": 0,
        "education_level": "Bachelor",
        "ai_analysis": {
            "name": "Karim Benali",
            "email": "karim.benali@example.com",
            "profile_summary": "Karim is a third-year Computer Science student at the University of Algiers, motivated and eager to gain his first professional experience abroad. While he lacks professional internship experience, he has built several personal projects demonstrating initiative. His main challenges are limited English proficiency and no professional Python exposure, which represent areas requiring attention.",
            "experience_years": 0,
            "education_level": "Bachelor",
            "education_analysis": "Karim is in his third year of a Bachelor's in Computer Science with a GPA of 13.5/20. His curriculum covers algorithms, data structures, and web development fundamentals, providing a solid theoretical base.",
            "experience_analysis": "Karim has no professional internship experience. However, he built a personal portfolio website using Flask and a small task-management app in Python, which he published on GitHub. These self-initiated projects demonstrate curiosity and a learning-oriented mindset, but do not substitute for professional delivery experience.",
            "soft_skills_analysis": "Karim demonstrates self-motivation through his independent projects. However, his CV shows limited evidence of collaborative work or cross-functional communication, which is a gap for a team-based internship.",
            "strengths_analysis": "Strong foundational knowledge in algorithms and data structures. Personal projects in Python/Flask show initiative. Highly motivated to prove himself internationally.",
            "weaknesses_analysis": "No professional internship experience is Karim's primary gap. His English is listed as 'intermediate' with no certification provided; this may hinder communication in a German team environment. No evidence of version control (Git) usage.",
            "risk_assessment": "Medium risk. Karim has the technical curiosity to succeed but requires more structure and mentoring than an average intern. The language barrier and lack of collaborative experience could slow his integration. Boarding advisors should probe language readiness carefully.",
            "languages": [
                {"language": "Arabic", "level": "Native", "evidence": "Native language"},
                {"language": "French", "level": "B1", "evidence": "French listed as second language"},
                {"language": "English", "level": "B1", "evidence": "Self-assessed as intermediate, no certification"},
            ],
            "skills": [
                {"name": "Python", "category": "Tech Stack", "level": 1, "level_label": "Basic", "evidence": "Built personal Flask task-management app (personal GitHub project)", "requirement_desc": "Core language for backend development"},
                {"name": "Git", "category": "Tech Stack", "level": 1, "level_label": "Basic", "evidence": "Not explicitly mentioned; inferred from GitHub profile", "requirement_desc": "Version control and collaboration"},
                {"name": "Communication", "category": "Soft Skills", "level": 1, "level_label": "Basic", "evidence": "No evidence of team or presentation experience on CV", "requirement_desc": "Cross-team collaboration"},
                {"name": "English", "category": "Language", "level": 2, "level_label": "Average", "evidence": "Self-assessed as intermediate, no formal certification provided", "requirement_desc": "Working language in international team"},
            ],
            "compatibility_checks": [
                {"criteria": "Education Level", "status": "compatible", "explanation": "Currently completing a Bachelor's in CS — meets the minimum academic requirement for a junior internship role."},
                {"criteria": "Years of Experience", "status": "incompatible", "explanation": "Zero professional internship experience. Personal projects exist but do not constitute formal professional delivery."},
                {"criteria": "Communication Skills", "status": "partial", "explanation": "Intermediate English (self-assessed, uncertified) and no evidence of collaborative projects raise concerns about professional communication readiness."},
                {"criteria": "International Readiness", "status": "partial", "explanation": "No prior international exposure documented. Motivation is expressed but unsubstantiated by actions such as language courses or exchange programmes."},
                {"criteria": "Technical Skills", "status": "partial", "explanation": "Python basics confirmed via personal projects, but no Git, no CI/CD, and no professional context — significantly below TechNova's typical intern baseline."},
            ],
            "compatibility_score": 55,
            "risk_level": "Medium",
        },
    },
    # ── Marketing Hub Paris ──
    {
        "company_name": "Marketing Hub Paris",
        "name": "Sofia Lindqvist",
        "email": "sofia.l@example.com",
        "phone": "+46 70 123 45 67",
        "status": "done",
        "compatibility_score": 91,
        "risk_level": "Low",
        "experience_years": 2,
        "education_level": "Master",
        "ai_analysis": {
            "name": "Sofia Lindqvist",
            "email": "sofia.l@example.com",
            "profile_summary": "Sofia is a Swedish marketing professional completing a dual Master's in Digital Marketing and Communication at Stockholm University. With two years of practical experience managing social media accounts and running paid campaigns, she is an exceptionally strong match for the Marketing Hub Paris internship position. Her trilingual profile (English, French, Swedish) is a major differentiator.",
            "experience_years": 2,
            "education_level": "Master",
            "education_analysis": "Sofia is completing a dual Master's degree combining Digital Marketing and Strategic Communication, with a specialisation in luxury brand management — directly relevant to Marketing Hub Paris's client portfolio.",
            "experience_analysis": "Sofia managed social media channels for an e-commerce brand (60K+ followers), grew organic reach by 40% in 6 months, and ran Meta Ads campaigns with budgets up to €5,000/month. She also completed a 6-month internship at a Stockholm PR agency handling 4 international accounts.",
            "soft_skills_analysis": "Sofia is an exceptional communicator with demonstrated client-facing experience. Her project management skills are evidenced by simultaneous management of 4 client accounts during her PR internship.",
            "strengths_analysis": "Trilingual profile, luxury brand marketing exposure, and measurable social media results (40% organic growth) make Sofia a top-tier candidate. Her French proficiency gives her a direct cultural advantage for the Paris placement.",
            "weaknesses_analysis": "Sofia's experience is predominantly B2C; Marketing Hub Paris also serves B2B clients. This is a minor gap that can be addressed through onboarding.",
            "risk_assessment": "Extremely low risk. Sofia brings experience, language skills, and cultural fit that go beyond typical intern expectations. She is likely to add immediate value from day one.",
            "languages": [
                {"language": "Swedish", "level": "Native", "evidence": "Swedish native speaker"},
                {"language": "English", "level": "C2", "evidence": "Cambridge C2 Proficiency certificate"},
                {"language": "French", "level": "B2", "evidence": "DELF B2 certificate obtained 2023"},
            ],
            "skills": [
                {"name": "Social Media", "category": "Marketing", "level": 3, "level_label": "Strong", "evidence": "Managed 60K-follower account, 40% organic growth in 6 months", "requirement_desc": "Core requirement for digital marketing role"},
                {"name": "French", "category": "Language", "level": 3, "level_label": "Strong", "evidence": "DELF B2 certificate 2023", "requirement_desc": "Working language in Paris office"},
                {"name": "Excel", "category": "Tools", "level": 3, "level_label": "Strong", "evidence": "Used Excel for weekly KPI reporting across 4 client accounts", "requirement_desc": "Reporting and data analysis"},
                {"name": "Communication", "category": "Soft Skills", "level": 3, "level_label": "Strong", "evidence": "Client-facing role managing 4 international accounts at PR agency", "requirement_desc": "Client and team communication"},
            ],
            "compatibility_checks": [
                {"criteria": "Education Level", "status": "compatible", "explanation": "Dual Master's in Digital Marketing and Communication — exceeds the educational requirement."},
                {"criteria": "Years of Experience", "status": "compatible", "explanation": "2 years of combined professional and internship experience in digital marketing."},
                {"criteria": "Communication Skills", "status": "compatible", "explanation": "C2 English and B2 French with client-facing experience across international accounts."},
                {"criteria": "International Readiness", "status": "compatible", "explanation": "Multilingual, has worked with international clients, and is actively seeking a Paris placement."},
                {"criteria": "Technical Skills", "status": "compatible", "explanation": "Social media management, Meta Ads, Excel — all core tools for the Digital Marketing Intern role are confirmed."},
            ],
            "compatibility_score": 91,
            "risk_level": "Low",
        },
    },
    # ── LogiTrans Barcelona ──
    {
        "company_name": "LogiTrans Barcelona",
        "name": "Omar Hassan",
        "email": "omar.h@example.com",
        "phone": "+212 600 789 456",
        "status": "done",
        "compatibility_score": 38,
        "risk_level": "High",
        "experience_years": 0,
        "education_level": "Bachelor",
        "ai_analysis": {
            "name": "Omar Hassan",
            "email": "omar.h@example.com",
            "profile_summary": "Omar is a final-year Bachelor's student in Business Administration from Casablanca. While he presents as motivated, his CV reveals significant gaps relative to the LogiTrans Barcelona requirements: no experience in logistics or supply chain, no English certification, no Spanish, and no Data Analysis experience. The placement carries a high risk of underperformance.",
            "experience_years": 0,
            "education_level": "Bachelor",
            "education_analysis": "Omar is completing a Bachelor's in Business Administration with a general management focus. His curriculum includes basic accounting, management principles, and business law — with no specialisation in supply chain or logistics.",
            "experience_analysis": "Omar completed a 2-month summer internship at a local retail company in Casablanca assisting with inventory counts. No data analysis or supply chain project is documented.",
            "soft_skills_analysis": "Limited evidence of communication skills in English or Spanish. No leadership or collaborative project evidence found on the CV.",
            "strengths_analysis": "Omar shows willingness to take on new challenges. His internship experience, though brief, shows he has some exposure to inventory management basics.",
            "weaknesses_analysis": "Critical gaps: no Spanish, no English certification, no prior exposure to data or supply chain tools, and only 2 months of tangentially relevant experience. These gaps represent multiple simultaneous onboarding challenges.",
            "risk_assessment": "High risk. Without Spanish (the working language) and with no supply chain or data analysis background, Omar would require disproportionate mentoring resources and is unlikely to be productive within the internship window. Boarding advisors should discuss whether additional preparation is required before this placement.",
            "languages": [
                {"language": "Arabic", "level": "Native", "evidence": "Native language"},
                {"language": "French", "level": "B2", "evidence": "Listed as professional proficiency"},
                {"language": "English", "level": "A2", "evidence": "Self-assessed as basic, no certification"},
            ],
            "skills": [
                {"name": "Excel", "category": "Tools", "level": 1, "level_label": "Basic", "evidence": "Used Excel for inventory tracking during retail internship", "requirement_desc": "KPI reporting and data analysis"},
                {"name": "Communication", "category": "Soft Skills", "level": 1, "level_label": "Basic", "evidence": "No documented communication experience beyond course work", "requirement_desc": "Team and stakeholder communication"},
                {"name": "Data Analysis", "category": "Analytics", "level": 1, "level_label": "Basic", "evidence": "No data analysis experience documented", "requirement_desc": "Core function of the supply chain analyst role"},
            ],
            "compatibility_checks": [
                {"criteria": "Education Level", "status": "partial", "explanation": "Business Administration degree is broadly relevant but lacks any supply chain or logistics specialisation."},
                {"criteria": "Years of Experience", "status": "incompatible", "explanation": "Only 2 months of tangentially relevant internship experience — far below the 6-month minimum expected for this role."},
                {"criteria": "Communication Skills", "status": "incompatible", "explanation": "No English certification and no Spanish — both are required working languages at LogiTrans Barcelona."},
                {"criteria": "International Readiness", "status": "partial", "explanation": "Omar has expressed motivation but has no documented international exposure or language preparation for a Spanish-speaking environment."},
                {"criteria": "Technical Skills", "status": "incompatible", "explanation": "Basic Excel only — no data analysis tools, supply chain software, or relevant analytical experience found on CV."},
            ],
            "compatibility_score": 38,
            "risk_level": "High",
        },
    },
]


def seed():
    app = create_app()
    with app.app_context():
        db.create_all()

        # Seed companies
        company_map = {}
        for c_data in COMPANIES:
            existing = Company.query.filter_by(name=c_data["name"]).first()
            if existing:
                company_map[c_data["name"]] = existing
                print(f"  [skip] Company already exists: {c_data['name']}")
                continue
            company = Company(
                name=c_data["name"],
                industry=c_data["industry"],
                location=c_data["location"],
                description=c_data["description"],
                website=c_data.get("website"),
                min_experience_years=c_data.get("min_experience_years", 0),
            )
            company.required_skills_list = c_data.get("required_skills", [])
            company.job_requirements_dict = c_data.get("job_requirements", {})
            db.session.add(company)
            db.session.flush()
            company_map[c_data["name"]] = company
            print(f"  [+] Created company: {c_data['name']}")

        db.session.commit()

        # Seed candidates
        for c_data in CANDIDATES:
            company = company_map.get(c_data["company_name"])
            if not company:
                print(f"  [!] Company not found: {c_data['company_name']}")
                continue
            existing = Candidate.query.filter_by(email=c_data["email"]).first()
            if existing:
                print(f"  [skip] Candidate already exists: {c_data['name']}")
                continue
            candidate = Candidate(
                company_id=company.id,
                name=c_data["name"],
                email=c_data.get("email"),
                phone=c_data.get("phone"),
                status=c_data.get("status", "done"),
                compatibility_score=c_data.get("compatibility_score"),
                risk_level=c_data.get("risk_level"),
                experience_years=c_data.get("experience_years"),
                education_level=c_data.get("education_level"),
                cv_path=c_data.get("cv_path", "uploads/default_cv.pdf"),
            )
            candidate.ai_analysis_dict = c_data.get("ai_analysis", {})
            db.session.add(candidate)
            print(f"  [+] Created candidate: {c_data['name']} → {c_data['company_name']}")

        db.session.commit()
        print("\n✓ Seed complete.")


if __name__ == "__main__":
    seed()
