"""
Report generation service.
Generates PDF and CSV reports for individual candidates or full company batches.
Uses ReportLab for PDF and Python's built-in csv module.
"""
import csv
import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)
from reportlab.platypus import PageBreak


# ─── Colour palette ────────────────────────────────────────────────────────────
PRIMARY = colors.HexColor("#1E3A5F")      # Dark navy
ACCENT = colors.HexColor("#2563EB")       # Blue
SUCCESS = colors.HexColor("#16A34A")      # Green
WARNING = colors.HexColor("#D97706")      # Amber
DANGER = colors.HexColor("#DC2626")       # Red
LIGHT_BG = colors.HexColor("#F8FAFC")    # Very light grey
BORDER = colors.HexColor("#E2E8F0")


def _risk_color(risk: str):
    mapping = {"Low": SUCCESS, "Medium": WARNING, "High": DANGER}
    return mapping.get(risk, ACCENT)


def _status_color(status: str):
    mapping = {"compatible": SUCCESS, "partial": WARNING, "incompatible": DANGER}
    return mapping.get(status, ACCENT)


def _status_symbol(status: str) -> str:
    mapping = {"compatible": "✓", "partial": "~", "incompatible": "✗"}
    return mapping.get(status, "?")


def _level_bars(level: int, max_level: int = 3) -> str:
    filled = "■" * level
    empty = "□" * (max_level - level)
    return filled + empty


# ─── PDF – Candidate Report ────────────────────────────────────────────────────

def generate_candidate_pdf(candidate: dict, company: dict) -> bytes:
    """
    Generate a full-page PDF report for a single candidate.
    Returns raw PDF bytes.
    """
    analysis = candidate.get("ai_analysis") or {}
    if isinstance(analysis, str):
        import json
        analysis = json.loads(analysis) if analysis else {}

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("Title", parent=styles["Heading1"], textColor=PRIMARY, fontSize=20)
    h2_style = ParagraphStyle("H2", parent=styles["Heading2"], textColor=PRIMARY, fontSize=13, spaceBefore=12)
    body_style = ParagraphStyle("Body", parent=styles["Normal"], fontSize=9, leading=14)
    muted_style = ParagraphStyle("Muted", parent=styles["Normal"], fontSize=8, textColor=colors.grey)
    bold_style = ParagraphStyle("Bold", parent=styles["Normal"], fontSize=9, fontName="Helvetica-Bold")

    story = []

    # ── Header ────
    story.append(Paragraph(f"Candidate Analysis Report", title_style))
    story.append(Paragraph(
        f"Generated by Boarding AI Backoffice &nbsp;·&nbsp; {datetime.now().strftime('%B %d, %Y')}",
        muted_style,
    ))
    story.append(HRFlowable(width="100%", thickness=1, color=BORDER, spaceAfter=8))

    # ── Candidate + Company Info ────
    info_data = [
        ["Candidate", analysis.get("name") or candidate.get("name", "—"),
         "Company", company.get("name", "—")],
        ["Email", analysis.get("email") or candidate.get("email", "—"),
         "Industry", company.get("industry", "—")],
        ["Phone", analysis.get("phone") or candidate.get("phone", "—"),
         "Location", company.get("location", "—")],
        ["Experience", f"{candidate.get('experience_years', '—')} years",
         "Risk Level", candidate.get("risk_level", "—")],
    ]
    info_table = Table(info_data, colWidths=[3 * cm, 6 * cm, 3 * cm, 5 * cm])
    info_table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (2, 0), (2, -1), "Helvetica-Bold"),
        ("TEXTCOLOR", (0, 0), (0, -1), PRIMARY),
        ("TEXTCOLOR", (2, 0), (2, -1), PRIMARY),
        ("BACKGROUND", (0, 0), (-1, -1), LIGHT_BG),
        ("GRID", (0, 0), (-1, -1), 0.5, BORDER),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(info_table)
    story.append(Spacer(1, 0.4 * cm))

    # ── Compatibility Score ────
    score = candidate.get("compatibility_score") or analysis.get("compatibility_score", 0)
    risk = candidate.get("risk_level") or analysis.get("risk_level", "Medium")
    score_data = [[
        Paragraph(f"<b>Compatibility Score</b>", bold_style),
        Paragraph(f"<font size=18><b>{score}%</b></font>", ParagraphStyle("Score", textColor=_risk_color(risk), fontSize=18, fontName="Helvetica-Bold")),
        Paragraph(f"<b>Risk Level</b>", bold_style),
        Paragraph(f"<b>{risk}</b>", ParagraphStyle("Risk", textColor=_risk_color(risk), fontSize=11, fontName="Helvetica-Bold")),
    ]]
    score_table = Table(score_data, colWidths=[4 * cm, 4 * cm, 4 * cm, 5 * cm])
    score_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), LIGHT_BG),
        ("BOX", (0, 0), (-1, -1), 1.5, ACCENT),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
    ]))
    story.append(score_table)
    story.append(Spacer(1, 0.3 * cm))

    # ── Profile Summary ────
    if analysis.get("profile_summary"):
        story.append(Paragraph("Profile Summary", h2_style))
        story.append(Paragraph(analysis["profile_summary"], body_style))

    # ── Compatibility Checks ────
    checks = analysis.get("compatibility_checks", [])
    if checks:
        story.append(Paragraph("Compatibility Analysis", h2_style))
        check_data = [["Criteria", "Status", "Explanation"]]
        wrap_style = ParagraphStyle("Wrap", parent=body_style, fontSize=8, wordWrap='CJK')
        for c in checks:
            sym = _status_symbol(c.get("status", ""))
            check_data.append([
                Paragraph(c.get("criteria") or "", wrap_style),
                sym,
                Paragraph(c.get("explanation") or "", wrap_style),
            ])
        check_table = Table(check_data, colWidths=[4.5 * cm, 1.5 * cm, 11 * cm])
        check_style = [
            ("BACKGROUND", (0, 0), (-1, 0), PRIMARY),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.3, BORDER),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]
        for i, c in enumerate(checks, start=1):
            color = _status_color(c.get("status", ""))
            check_style.append(("TEXTCOLOR", (1, i), (1, i), color))
            check_style.append(("FONTNAME", (1, i), (1, i), "Helvetica-Bold"))
            if i % 2 == 0:
                check_style.append(("BACKGROUND", (0, i), (-1, i), LIGHT_BG))
        check_table.setStyle(TableStyle(check_style))
        story.append(check_table)
        story.append(Spacer(1, 0.3 * cm))

    # ── Skills ────
    skills = analysis.get("skills", [])
    if skills:
        story.append(Paragraph("Skills & Evidence", h2_style))
        skill_data = [["Skill", "Category", "Level", "Evidence"]]
        wrap_style = ParagraphStyle("Wrap", parent=body_style, fontSize=8, wordWrap='CJK')
        for s in skills:
            skill_data.append([
                Paragraph(s.get("name") or "", wrap_style),
                Paragraph(s.get("category") or "", wrap_style),
                f"{_level_bars(s.get('level', 1))} {s.get('level_label') or ''}",
                Paragraph(s.get("evidence") or "", wrap_style),
            ])
        skill_table = Table(skill_data, colWidths=[3.5 * cm, 3 * cm, 3.5 * cm, 7 * cm])
        skill_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), PRIMARY),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.3, BORDER),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        story.append(skill_table)
        story.append(Spacer(1, 0.3 * cm))

    # ── Paragraph Analyses ────
    section_map = [
        ("Education", "education_analysis"),
        ("Experience", "experience_analysis"),
        ("Soft Skills", "soft_skills_analysis"),
        ("Strengths", "strengths_analysis"),
        ("Weaknesses & Gaps", "weaknesses_analysis"),
        ("Risk Assessment", "risk_assessment"),
    ]
    for label, key in section_map:
        text = analysis.get(key)
        if text:
            story.append(Paragraph(label, h2_style))
            story.append(Paragraph(text, body_style))

    # ── Languages ────
    languages = analysis.get("languages", [])
    if languages:
        story.append(Paragraph("Languages", h2_style))
        lang_data = [["Language", "Level", "Evidence"]]
        wrap_style = ParagraphStyle("Wrap", parent=body_style, fontSize=8, wordWrap='CJK')
        for lang in languages:
            if isinstance(lang, dict):
                lang_data.append([
                    Paragraph(lang.get("language") or "", wrap_style),
                    Paragraph(lang.get("level") or "", wrap_style),
                    Paragraph(lang.get("evidence") or "", wrap_style),
                ])
            else:
                lang_data.append([Paragraph(str(lang) or "", wrap_style), "", ""])
        lang_table = Table(lang_data, colWidths=[4 * cm, 3 * cm, 10 * cm])
        lang_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), PRIMARY),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.3, BORDER),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        story.append(lang_table)
        # Duplicate removed

    # ── Footer ────
    story.append(Spacer(1, 0.5 * cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER))
    story.append(Paragraph(
        "Boarding AI Backoffice · Confidential · For internal use only",
        ParagraphStyle("Footer", parent=styles["Normal"], fontSize=7, textColor=colors.grey, alignment=TA_CENTER),
    ))

    doc.build(story)
    return buffer.getvalue()


# ─── PDF – Company Batch Report ────────────────────────────────────────────────

def generate_company_pdf(company: dict, candidates: list[dict]) -> bytes:
    """Generate a summary PDF report for all candidates in a company."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, leftMargin=2 * cm, rightMargin=2 * cm,
                            topMargin=2 * cm, bottomMargin=2 * cm)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("Title", parent=styles["Heading1"], textColor=PRIMARY, fontSize=18)
    h2_style = ParagraphStyle("H2", parent=styles["Heading2"], textColor=PRIMARY, fontSize=12, spaceBefore=10)
    body_style = ParagraphStyle("Body", parent=styles["Normal"], fontSize=9, leading=14)
    muted_style = ParagraphStyle("Muted", parent=styles["Normal"], fontSize=8, textColor=colors.grey)

    story = []
    story.append(Paragraph(f"Company Candidates Report: {company.get('name', '')}", title_style))
    story.append(Paragraph(
        f"Generated {datetime.now().strftime('%B %d, %Y')} · {len(candidates)} candidate(s)",
        muted_style,
    ))
    story.append(HRFlowable(width="100%", thickness=1, color=BORDER, spaceAfter=8))

    # Summary table
    headers = ["#", "Name", "Score", "Risk", "Experience", "Education", "Status"]
    table_data = [headers]
    for i, c in enumerate(candidates, 1):
        table_data.append([
            str(i),
            c.get("name", "—"),
            f"{c.get('compatibility_score', '—')}%",
            c.get("risk_level", "—"),
            f"{c.get('experience_years', '—')} yrs",
            c.get("education_level", "—"),
            c.get("status", "—"),
        ])

    t = Table(table_data, colWidths=[1 * cm, 4.5 * cm, 2 * cm, 2 * cm, 2.5 * cm, 3.5 * cm, 2.5 * cm])
    ts = TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), PRIMARY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.3, BORDER),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
    ])
    for i, c in enumerate(candidates, 1):
        risk = c.get("risk_level", "")
        ts.add("TEXTCOLOR", (3, i), (3, i), _risk_color(risk))
        ts.add("FONTNAME", (3, i), (3, i), "Helvetica-Bold")
        if i % 2 == 0:
            ts.add("BACKGROUND", (0, i), (-1, i), LIGHT_BG)
    t.setStyle(ts)
    story.append(t)

    doc.build(story)
    return buffer.getvalue()


# ─── CSV ───────────────────────────────────────────────────────────────────────

def generate_candidates_csv(candidates: list[dict]) -> bytes:
    """Generate a flat CSV export for a list of candidates."""
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow([
        "ID", "Name", "Email", "Phone",
        "Compatibility Score", "Risk Level",
        "Experience Years", "Education Level",
        "Status", "Company ID", "CV Filename",
        "Created At",
    ])
    for c in candidates:
        writer.writerow([
            c.get("id"), c.get("name"), c.get("email"), c.get("phone"),
            c.get("compatibility_score"), c.get("risk_level"),
            c.get("experience_years"), c.get("education_level"),
            c.get("status"), c.get("company_id"), c.get("cv_filename"),
            c.get("created_at"),
        ])
    return output.getvalue().encode("utf-8-sig")  # BOM for Excel compatibility
